name: Bug Report
description: Report a bug or issue with the Last Tab Focus extension
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version of the extension
          required: true
        - label: I have tried disabling other extensions to rule out conflicts
          required: true

  - type: input
    id: chrome-version
    attributes:
      label: Chrome Version
      description: What version of Chrome are you using?
      placeholder: "e.g., Chrome 120.0.6099.71"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Last Tab Focus are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - ChromeOS
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: "Describe what happened..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Open Chrome with multiple tabs
        2. Switch between tabs to build history
        3. Close the active tab
        4. Notice that...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The extension should have..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: "Instead, the extension..."
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: |
        Please provide any relevant console logs from the service worker:
        1. Go to chrome://extensions/
        2. Find "Last Tab Focus" extension
        3. Click "service worker" inspection link
        4. Copy any error messages or relevant logs
      placeholder: "Paste console logs here..."
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: "Any additional information that might be helpful..."

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workarounds
        - High - Major functionality broken
        - Critical - Extension completely unusable
    validations:
      required: true